spring:
  application:
    name: project

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}

  sqs:
    name: ${AWS_SQS_NAME}

external-service:
  url: ${EXTERNAL_SERVICE_URL}
